###########################################################
### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website.
###########################################################

############################
# --- Required options --- #
############################
markdown: kramdown
kramdown:
  math_engine: mathjax
# Name of website
title: Blog Posts
# Your name to show in the footer
author: Filip MirkoviÄ‡

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"

################
# --- Logo --- #
################

# Favicon of the Kanagawa Great Wave
#favicon: "/assets/img/flows/kanagawa.jpg"

# Image to show in the navigation bar
avatar: "/assets/img/avatar.png"

# By default, the image is cut into a circle.
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "filip.mirkovic2211@gmail.com"
  rss: true
  github: mirxonius
  
rss-description: This website is a virtual proof that I'm awesome

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false
  reddit: false
  github: true

url-pretty: "FilipsWebsite.com"
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: false
navbar-var-length: false

######################################
# --- Colours / background image --- #
######################################

page-col: "#FFFFFF"
text-col: "#2baffb" #"#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#2B99FB"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

navbar-img: "/assets/img/bgimage.png"
footer-img: "/assets/img/bgimage.png"
page-img: null

#################################
# --- Web Analytics Section --- #
#################################

# gtag: "G-XXXXXXXXXX"

####################
# --- Comments --- #
####################

# Choose your preferred comment system here (Disqus, Utterances, Giscus, etc.)

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"

#################################################################################
# --- Internal Jekyll Settings --- #
#################################################################################

timezone: "Europe/Zagreb"
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap